---
docker_install_users: ["{{ ansible_user }}"]
docker_install_edition: ce
docker_install_packages:
  - "docker-{{ docker_install_edition }}"
  - "docker-{{ docker_install_edition }}-cli"
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
